//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktori
    {
        public Doktori()
        {
            this.kartoni = new HashSet<kartoni>();
            this.Pregledi = new HashSet<Pregledi>();
            this.Termini = new HashSet<Termini>();
        }
    
        public int IdDoktora { get; set; }
        public string Ime_ { get; set; }
        public string Prezime { get; set; }
        public System.DateTime Datum_rodjenja { get; set; }
        public string Mjesto_rodjenja { get; set; }
        public string Titula { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<kartoni> kartoni { get; set; }
        public virtual ICollection<Pregledi> Pregledi { get; set; }
        public virtual ICollection<Termini> Termini { get; set; }
    }
}
