//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Temini = new HashSet<Temini>();
        }
    
        public int Id { get; set; }
        public string Opis { get; set; }
        public System.DateTime Pocetak { get; set; }
        public System.DateTime Kraj { get; set; }
    
        public virtual ICollection<Temini> Temini { get; set; }
    }
}
