//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Image
    {
        public Image()
        {
            this.Karton = new HashSet<Karton>();
        }
    
        public int ImageId { get; set; }
        public int ImageSize { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }

        public HttpPostedFileBase File { get; set; }
        public virtual ICollection<Karton> Karton { get; set; }
    }
}
