//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Karton
    {
        public int IdKartona { get; set; }
        public Nullable<int> IdPacijenta { get; set; }
        [Required(ErrorMessage="Unesite polje")]
        [Display(Name="Mišljenje sprecijaliste")]
        [DataType(DataType.MultilineText)]
        public string Misljenje_specijaliste { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        [Display(Name="Datum zadnje izmjene")]
        public System.DateTime Datum_zadnje_ismjene { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        [DataType(DataType.MultilineText)]
        public string Dijagnoza { get; set; }
        [DataType(DataType.MultilineText)]
        public string Primjedba { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        [Display(Name="Sposobnost kretanja")]
        public string Sposobnost_kretanja { get; set; }
        [Display(Name = "Zarazna bolest")]
        public string Zarazna_bolest { get; set; }
        public Nullable<int> Slika { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
    }
}
