//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class kartoni
    {
        public kartoni()
        {
            this.Pregledi = new HashSet<Pregledi>();
        }
    
        public int IdKartona { get; set; }
        public int IdDoktora { get; set; }
        public int IdPacijenta { get; set; }
        public byte[] Ekg_slika { get; set; }
        public string Misljenje_specijaliste { get; set; }
        public System.DateTime Datum_zadnje_promjene { get; set; }
        public string Dijagnoza { get; set; }
        public string Primjedba { get; set; }
    
        public virtual Doktori Doktori { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
        public virtual ICollection<Pregledi> Pregledi { get; set; }
    }
}
