//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Pacijenti = new HashSet<Pacijenti>();
            this.Uposlenik = new HashSet<Uposlenik>();
        }
    
        public int IdKorisnika { get; set; }
        [Required(ErrorMessage="Unesite ime")]
        [Display(Name="Ime")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Unesite prezime")]
        [Display(Name = "Prezime")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Unesite ime oca")]
        [Display(Name = "Ime oca")]
        public string Ime_oca { get; set; }
        [Required(ErrorMessage = "Unesite broj lične karte")]
        [Display(Name = "Broj lične karte")]
        public string Broj_licne { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "Unesite datum rođenja")]
        [Display(Name = "Datum rođenja")]
        [DataType("Date")]
        public System.DateTime Datum_rodjenja { get; set; }
        [Required(ErrorMessage = "Unesite mjesto rođenja")]
        [Display(Name = "Mjesto rođenja")]
        public string Mjesto_rodjenja { get; set; }
        [Required(ErrorMessage = "Unesite prebivalište")]
        [Display(Name = "Prebivalište")]
        public string Prebivalište { get; set; }
        [Required(ErrorMessage = "Unesite username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Unesite password")]
        [DataType("Password")]
        public string Password { get; set; }
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Unesite JMBG")]
        public string JMBG { get; set; }
        public int idRole { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Pacijenti> Pacijenti { get; set; }
        public virtual ICollection<Uposlenik> Uposlenik { get; set; }
    }
}
