//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eOrdinacijaEntities1 : DbContext
    {
        public eOrdinacijaEntities1()
            : base("name=eOrdinacijaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Karton> Karton { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Nalaz> Nalaz { get; set; }
        public DbSet<Odjel> Odjel { get; set; }
        public DbSet<Oprema> Oprema { get; set; }
        public DbSet<Pacijenti> Pacijenti { get; set; }
        public DbSet<Pregled> Pregled { get; set; }
        public DbSet<Privilegije> Privilegije { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Soba> Soba { get; set; }
        public DbSet<Temini> Temini { get; set; }
        public DbSet<Uloge> Uloge { get; set; }
        public DbSet<Uposlenik> Uposlenik { get; set; }
    }
}
