//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaPodatakaEntities : DbContext
    {
        public BazaPodatakaEntities()
            : base("name=BazaPodatakaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Doktori> Doktori { get; set; }
        public DbSet<kartoni> kartoni { get; set; }
        public DbSet<Pacijenti> Pacijenti { get; set; }
        public DbSet<Pregledi> Pregledi { get; set; }
        public DbSet<Termini> Termini { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
