//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odjel
    {
        public Odjel()
        {
            this.Soba = new HashSet<Soba>();
            this.Uposlenik = new HashSet<Uposlenik>();
        }
    
        public int IdOdjela { get; set; }
        public string TipOdjela { get; set; }
        public int BrojSoba { get; set; }
    
        public virtual ICollection<Soba> Soba { get; set; }
        public virtual ICollection<Uposlenik> Uposlenik { get; set; }
    }
}
