//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Oprema
    {
        public Oprema()
        {
            this.Potroseno = new HashSet<Potroseno>();
        }
    
        public int IdOpreme { get; set; }
        [Required(ErrorMessage="Unesite polje")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        [Display(Name="Proizvoðaæ")]
        public string Proizvodjac { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        [Display(Name = "Godina proizvodnje")]
        public Nullable<int> Godina_proizvodnje { get; set; }
        [Required(ErrorMessage="Unesite polje")]
        public string Opis { get; set; }
        [Required(ErrorMessage = "Unesite polje")]
        public decimal Cjena { get; set; }
    
        public virtual ICollection<Potroseno> Potroseno { get; set; }
    }
}
