//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        public int IdOpreme { get; set; }
        public string Naziv { get; set; }
        public string Proizvodjac { get; set; }
        public string Model { get; set; }
        public Nullable<int> Godina_proizvodnje { get; set; }
        public string Opis { get; set; }
        public decimal Cjena { get; set; }
        public int idPregleda { get; set; }
    
        public virtual Pregled Pregled { get; set; }
    }
}
