//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijenti
    {
        public Pacijenti()
        {
            this.kartoni = new HashSet<kartoni>();
            this.Pregledi = new HashSet<Pregledi>();
            this.Termini = new HashSet<Termini>();
        }
    
        public int IdPacijenta { get; set; }
        [Required(ErrorMessage = "Unesite ime")]
        [Display(Name="Ime pacijenta")]
        public string Ime { get; set; }
        [Required(ErrorMessage="Unesite prezime")]
        [Display(Name = "Prezime pacijenta")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Unesite datum rođenja")]
        [DataType(DataType.Date)]
        [Display(Name="Datum rođenja")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Datum_rođenja { get; set; }
        [Required(ErrorMessage = "Unesite broj lične karte")]
        [Display(Name = "Broj lične karte")]
        public string Licna_karta { get; set; }
        [Required(ErrorMessage = "Unesite mjesto rođenja")]
        [Display(Name = "Mjesto rođenja")]
        public string Mjesto_rodjenja { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "Unesite mjesto prebivališta")]
        [Display(Name = "Mjesto prebivališta")]
        public string Mjesto_prebivališta { get; set; }
        [Required(ErrorMessage="Unesite ime oca")]
        [Display(Name="Ime oca")]
        public string Ime_oca { get; set; }

        public virtual ICollection<kartoni> kartoni { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Pregledi> Pregledi { get; set; }
        public virtual ICollection<Termini> Termini { get; set; }
    }
}
