//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potroseno
    {
        public Potroseno()
        {
            this.Pregled = new HashSet<Pregled>();
        }
    
        public int IdPotoseno { get; set; }
        public int Oprema { get; set; }
        public int Kolićina { get; set; }
        public string Jedinica { get; set; }
    
        public virtual Oprema Oprema1 { get; set; }
        public virtual ICollection<Pregled> Pregled { get; set; }
    }
}
