//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Pregled
    {
        public int idPregleda { get; set; }
        public System.DateTime Datum { get; set; }
        [Required(ErrorMessage="Unesite polje")]
        [Display(Name="Razlog posjete")]
        [DataType(DataType.MultilineText)]
        public string Razlog_posjete { get; set; }
        public string Simptomi { get; set; }
        public Nullable<int> Oprema { get; set; }
        public int idPacijenta { get; set; }
        public int IdUposlenika { get; set; }
    
        public virtual Pacijenti Pacijenti { get; set; }
        public virtual Potroseno Potroseno { get; set; }
        public virtual Uposlenik Uposlenik { get; set; }
    }
}
