//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregledi
    {
        public int IdPregleda { get; set; }
        public int Pregled_izvrsio { get; set; }
        public int Pacijent { get; set; }
        public System.DateTime Datum_pregleda { get; set; }
        public int Broj_kartona { get; set; }
        public Nullable<int> Cjena { get; set; }
    
        public virtual Doktori Doktori { get; set; }
        public virtual kartoni kartoni { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
    }
}
