//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregled
    {
        public Pregled()
        {
            this.Oprema1 = new HashSet<Oprema>();
        }
    
        public int idPregleda { get; set; }
        public System.DateTime Datum { get; set; }
        public string Razlog_posjete { get; set; }
        public string Simptomi { get; set; }
        public string Dijagnoza { get; set; }
        public Nullable<int> Oprema { get; set; }
        public int idPacijenta { get; set; }
        public int IdUposlenika { get; set; }
    
        public virtual ICollection<Oprema> Oprema1 { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
        public virtual Uposlenik Uposlenik { get; set; }
    }
}
