//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Privilegije
    {
        public Privilegije()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int idPrivilegije { get; set; }
        [Display(Name="Dodaj doktora")]
        public bool add_doktor { get; set; }
        [Display(Name = "Dodaj pacijenta")]
        public bool add_pacijent { get; set; }
        [Display(Name = "Briši doktora")]
        public bool del_doktor { get; set; }
        [Display(Name = "Briši pacijenta")]
        public bool del_pacijent { get; set; }
        [Display(Name = "Izmjeni doktora")]
        public bool modify_doktor { get; set; }
        [Display(Name = "Izmjeni pacijenta")]
        public bool modify_pacijent { get; set; }
        [Display(Name = "Izmjena privilegije")]
        public bool add_new_privilegije { get; set; }
        [Display(Name = "Pregled kartona")]
        public bool pregled_kartona { get; set; }
        [Display(Name = "Izmjena kartona")]
        public bool modify_kartona { get; set; }
        [Display(Name = "Ažuriranje opreme")]
        public bool ažuriranje_opreme { get; set; }
        [Display(Name = "Zakazivanje termina")]
        public bool zakazivanje_termina { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
