//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int idRole { get; set; }
        public int IdPrivilegije { get; set; }
        public int IdUloge { get; set; }
    
        public virtual ICollection<Korisnik> Korisnik { get; set; }
        public virtual Privilegije Privilegije { get; set; }
        public virtual Uloge Uloge { get; set; }
    }
}
