//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soba
    {
        public Soba()
        {
            this.Pacijenti = new HashSet<Pacijenti>();
        }
    
        public int IdSobe { get; set; }
        public int idOdjela { get; set; }
        public int BrojKreveta { get; set; }
    
        public virtual Odjel Odjel { get; set; }
        public virtual ICollection<Pacijenti> Pacijenti { get; set; }
    }
}
