//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    public partial class Soba
    {
        public Soba()
        {
            this.Pacijenti = new HashSet<Pacijenti>();
        }

        public int IdSobe { get; set; }
        [Required(ErrorMessage = "Polje obavezno!")]
        [Display(Name="Odjel")]
        [Remote("ProvjeriSobe", "Korisnik", ErrorMessage = "Odjel je popunjen")]
        public int idOdjela { get; set; }
        [Display(Name = "Broj kreveta")]
        [Required(ErrorMessage = "Polje obavezno!")]
        public int BrojKreveta { get; set; }
        [Required(ErrorMessage="Polje obavezno!")]
        [Display(Name = "Broj sobe")]
        public string brojSobe { get; set; }
   
        public virtual Odjel Odjel { get; set; }
        public virtual ICollection<Pacijenti> Pacijenti { get; set; }
    }
}
