//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termini
    {
        
        public int IdTermina { get; set; }
        public int IdDoktora { get; set; }
        [Required(ErrorMessage = "Odaberite pacijenta")]
        [Display(Name = "Odaberite pacijenta")]
        public int IdPacijenta { get; set; }
        [Required(ErrorMessage = "Unesite datum")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [FutureDateValidator(ErrorMessage = "Datum mora biti u buduènosti")]
        
        public System.DateTime DatumTermina { get; set; }
    
        public virtual Doktori Doktori { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
    }
}
