//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uloge
    {
        public Uloge()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int idUloge { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
