//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrdinacija_Baze
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Uposlenik
    {
        public Uposlenik()
        {
            this.Nalaz = new HashSet<Nalaz>();
            this.Pregled = new HashSet<Pregled>();
            this.Temini = new HashSet<Temini>();
        }
    
        public int idUposlenika { get; set; }
        [Required(ErrorMessage="Unesite titulu")]
        public string Titula { get; set; }
        [Required(ErrorMessage = "Unesite zanimanje")]
        public string Zanimanje { get; set; }
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage="Upišite nešto o uposleniku")]
        public string Biografija { get; set; }
        public int idKorisnika { get; set; }
        [Display(Name="Odjel")]
        public int idOdjela { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual ICollection<Nalaz> Nalaz { get; set; }
        public virtual Odjel Odjel { get; set; }
        public virtual ICollection<Pregled> Pregled { get; set; }
        public virtual ICollection<Temini> Temini { get; set; }
    }
}
